signedit:    
    ignorecreative: true
    
    invertmouse: false
    
    log:
        filename: signedit.log
        
    commands:
        logtofile: false
        logtoconsole: true  
    
    colorsonplace: 
        enabled: true
        usepermission: false
        
    locale: enUS

    metrics: true
    
    fireBlockBreakPlace: true